version: '2.1'

services:
  cookie3:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/cookie2/cookie3
    ports:
      - $SERVER_PORT:$SERVER_PORT
